#!/bin/bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/core/utils.sh"
. "$DIR/core/vanilla.sh"

case "$1" in
  --status | -s)
    print_status
    exit 0
    ;;
  --attach | -a)
    attach_container "$@"
    exit 0
    ;;
  --logs | -l)
    show_logs "$@"
    exit 0
    ;;
  --start | -sc)
    start_container "$@"
    exit 0
    ;;
  --set-property | -sp)
    set_property "$@"
    exit 0
    ;;
  --remove | -rm)
    remove_container "$@"
    exit 0
    ;;
  --restart | -rs)
    restart_container "$@"
    exit 0
    ;;
  --vanilla | -v)
    run_vanilla "$@"
    exit 0
    ;;
  *)
    no_mode "$@"
    exit 0
    ;;
esac
